### PR TITLE
Add Serial Spinner with an AB Rotary encoder through User_IO, and Keyboard Input Support

### PR DESCRIPTION
**Pull request by neurorulez**
I use a 600 pulses AB Rotatory encoder (Incremental) about 15$ in amazon/aliexpress
Connect Phase-A to USER_IO[2] - PIN_AH12
Connect Phase-B to USER_IO[1] - PIN_AH9
Connect GND, VCC... and GO!
IMG_20200122_094713_713

IMG_20200122_094723_719
Arkanoid

For fire i use a standart arcade button.
Conenct Swich Button to USER_IO[3] - PIN_AH11
Connect GND...

### CODE REVIEW

**Comment by sorgelig** [comment]
Add $5 for Arduino Micro and use USB connection.
Currently it's not well standardized rotary encoders/spinners due to only couple cores really need it, but i plan to standardize it. I'm working on teensy 3.2 FW for one joystick which includes spinner. So I'm at about the same topic. 
For spinners there will be left/right pulses but i think it's better to simulate the analog X axis.
There is no point to create very custom interface while it can be easily done over USB and used in other cores too.
Also other retro controllers like A2600 paddle can use the same way through USB adapters.

**Comment by neurorulez** [comment]
Ohh, i like the retro feeling of the direct conexion to the core like the snac protocol in nes and snes. But im sorry if you donk like it.
Thanks for you great job in the mister project.

**Comment by sorgelig** [comment]
ok, i will add your changes. This core uses such encoder natively anyway.
But i don't understand why you use raw_encoder while direct connection of A/B to spinner signals should work.

**Comment by sorgelig** [comment]
Also i think it would be more logical to use USER_IN[1:0] for encoder.

**Comment by neurorulez** [comment]
I use that process to downgrqde the pulses rate, arkanoid have a 300 pulse rotary encoder but  I buyed a 600 pulses because my first proyect was super breakout and that uses a 600 pulses system, and you can use a 600 to lower rste pulses,.but not use a 300 pulses encoder works like 600 ome.. (i will make a pull request on that another day, because the signal goes direct to the core).
And.the use of that pines was because i get the pines stasrting in user_io(1), no problem if you want to change fire button from 3 to 0 or encoder to 1:0 :)

**Comment by sorgelig** [comment]
I've added support for USER_IO rotary encoder, but it's direct connection. If it doesn't work well, then can reduce the resolution.
try it anyway

**Comment by neurorulez** [comment]
The direct conection works but is too fast to play, you need to downgrade the signal to make it playable, i will record a video to show that. Yo can make an option of direct or downgrade signal to use one encoder of high puse rate to use in all cores that uses one. 
I will try it and comment to you.

**Comment by neurorulez** [comment]
Tryed, its too fast to be playable in the 3 spinner levels.
I attach a video-gif
t-video5859409769223161723

**Comment by sorgelig** [comment]
i see. 
Spinner options are only for USB version.
USER_IO version is connected directly (and always enabled). I will add the way you've used, although it's not a genuine anymore.

**Comment by neurorulez** [comment]
Tested, Works fine. 
The conexion with the pulse downgrade is almost genuine. The ab encoder works like the original, but the signal is halved more or less... The sensation when you play with the encoder is great.
I close the pull request because yours works fine. 
Thans again for your work. I will try to help in Mister project.

t_video5861661569036846824

**Comment by sorgelig** [comment]
It seems it still too sensitive according to your video. Probably should be halved further. 
But i have no such encoder to test.

**Comment by neurorulez** [comment]
I think its ok.
I seek in YouTube for a real gameplay: https://youtu.be/5FZDPnrYIIo
And this is the core in video-gif.
t_video5861661569036846851

**Pull request closed without merging**
